// <auto-generated />
using System;
using EncryptedChatClient.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EncryptedChatClient.Migrations
{
    [DbContext(typeof(ChatLocalDB))]
    [Migration("20231125115313_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("EncChatCommonLib.Models.ChatMessage", b =>
                {
                    b.Property<string>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MsgContent")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MsgDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MsgStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MsgType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReceiverId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderId")
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId");

                    b.HasIndex("ConversationId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("EncChatCommonLib.Models.Conversation", b =>
                {
                    b.Property<string>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WithWhomId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WithWhomName")
                        .HasColumnType("TEXT");

                    b.HasKey("ConversationId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("EncChatCommonLib.Models.ChatMessage", b =>
                {
                    b.HasOne("EncChatCommonLib.Models.Conversation", "Conversation")
                        .WithMany("ChatMessages")
                        .HasForeignKey("ConversationId");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("EncChatCommonLib.Models.Conversation", b =>
                {
                    b.Navigation("ChatMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
